### ISSUE TITLE
bcachefs fsck journal repair stuck: cannot allocate memory

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#147]
I have a testing set of bcachefs drives.  Unfortunately, while doing tests, the NFS subsystem hung and caused an NMI interrupt, so I had to force a PC reset.  When rebooting, it gave the following error for 3cf34905-b04f-449c-b3c0-93f686c4bda9:
```
[    8.380986] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): journal checksum bad, sector 1043456, fixing
[    8.380988] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): unknown journal entry version 1118932277
[    8.802396] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): Error in recovery: cannot allocate memory (4)
```
the other drives are OK (never mind about clean shutdown, I already rebooted it a 2nd time):
```
[    7.154468] bcachefs (6487fff2-c26e-4d19-916f-8dba75737547): recovering from clean shutdown, journal seq 221
[    8.165388] bcachefs (6487fff2-c26e-4d19-916f-8dba75737547): mounted with opts: data_checksum=none,foreground_target=SSD,background_target=HDD,promote_target=SSD,fix_errors
[    8.380986] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): journal checksum bad, sector 1043456, fixing
[    8.380988] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): unknown journal entry version 1118932277
[    8.802396] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): Error in recovery: cannot allocate memory (4)
[    8.999363] bcachefs (698c9dbd-eadd-4041-9574-45ab0fb3df61): recovering from clean shutdown, journal seq 228218
[   23.324997] bcachefs (698c9dbd-eadd-4041-9574-45ab0fb3df61): mounted with opts: data_checksum=none,foreground_target=SSD,background_target=HDD,promote_target=SSD,fix_errors
```
I tried to repair the error using bcachefs fsck
```
linuxserver # bcachefs fsck /dev/disk/by-partlabel/nvmsoftCache /dev/disk/by-partlabel/sassoftcache /dev/disk/by-partlabel/satasoft /dev/disk/by-id/scsi-232455ca500d00000
journal checksum bad, sector 1043456: fix? (y,n) y
unknown journal entry version 1118932277
Error in recovery: cannot allocate memory (4)
error opening /dev/disk/by-partlabel/nvmsoftCache: Input/output error
linuxserver # bcachefs fsck /dev/disk/by-partlabel/sassoftcache /dev/disk/by-partlabel/satasoft /dev/disk/by-id/scsi-232455ca500d00000 /dev/disk/by-partlabel/nvmsoftCache 
journal checksum bad, sector 1043456: fix? (y,n) y
unknown journal entry version 1118932277
Error in recovery: cannot allocate memory (4)
error opening /dev/disk/by-partlabel/sassoftcache: Input/output error
bcachefs fsck --reconstruct-alloc /dev/disk/by-partlabel/sassoftcache /dev/disk/by-partlabel/satasoftw /dev/disk/by-id/scsi-232455ca500d00000 /dev/disk/by-partlabel/nvmSoftwareCache 
bcachefs: unrecognized option '--reconstruct-alloc'
journal checksum bad, sector 1043456: fix? (y,n) y
unknown journal entry version 1118932277
Error in recovery: cannot allocate memory (4)
error opening /dev/disk/by-partlabel/sassoftcache: Input/output error
```
so, I'm quite sure the data is still there, but is inaccessible due to a corrupt journal on one of the disks.

I attached the superblock of each and every device, but is there a way to find out which journal is corrupt? and which ones could be fixed?

[superblocks.tar.gz](https://github.com/koverstreet/bcachefs/files/5109504/superblocks.tar.gz)

**Comment by koverstreet** [comment]
I can definitely at least improve those error messages, I'll do that.

**Comment by koverstreet** [comment]
I just pushed some improvements to the relevant code - can you try with the updated version and report back?

**Comment by jpsollie** [comment]
Thank you for the improvements!
I still get the error, but it indeed shows some debug info:

  19.819333] bcachefs (6487fff2-c26e-4d19-916f-8dba75737547): mounted with opts: data_checksum=none,foreground_target=SSD,background_target=HDD,promote_target=SSD,fix_errors
[   20.009845] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1043456 seq 16630: journal checksum bad, fixing
[   20.009847] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1043616 seq 144959613534272244: unknown journal entry version 1118932277, fixing
[   20.188960] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1043696 seq 17274: journal checksum bad, fixing
[   20.214421] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1041408 seq 17057: journal checksum bad, fixing
[   20.216289] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1042232 seq 16982: journal entry too big (29285984768 bytes), fixing
[   20.255694] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1037312 seq 7825: journal checksum bad, fixing
[   20.257448] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1037800 seq 8087: journal checksum bad, fixing
[   20.257451] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1037992 seq 8099: journal checksum bad, fixing
[   20.267334] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1035264 seq 8973: journal checksum bad, fixing
[   20.267336] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1035392 seq 8974: journal checksum bad, fixing
[   20.267337] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1035400 seq 8975: journal checksum bad, fixing
[   20.267339] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1035408 seq 8976: journal checksum bad, fixing
[   20.267339] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): Ratelimiting new instances of previous error
[   20.333553] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1031224 seq 2702: unknown journal entry version 1595447, fixing
[   20.396025] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1025144 seq 3127: unknown journal entry version 44495, fixing
[   20.408947] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1023016 seq 3179: unknown journal entry version 48956, fixing
[   20.450186] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sdd sector 1019176 seq 16758702572731357210: unknown journal entry version 137405203, fixing
[   20.474644] kworker/u32:0: vmalloc: allocation failure: 28971103304 bytes, mode:0xcc0(GFP_KERNEL), nodemask=(null),cpuset=/,mems_allowed=0
[   20.474650] CPU: 4 PID: 7 Comm: kworker/u32:0 Not tainted 5.8.3+ #2
[   20.474651] Hardware name: Gigabyte Technology Co., Ltd. X570 UD/X570 UD, BIOS F20 07/07/2020
[   20.474666] Workqueue: events_unbound bch2_journal_read_device [bcachefs]
[   20.474667] Call Trace:
[   20.474673]  dump_stack+0x57/0x70
[   20.474677]  warn_alloc.cold+0x78/0xd9
[   20.474680]  ? __vunmap+0x228/0x260
[   20.474682]  __vmalloc_node_range+0x19e/0x280
[   20.474684]  __vmalloc+0x55/0x60
[   20.474694]  ? bch2_journal_read_device+0x8fd/0xab0 [bcachefs]
[   20.474705]  bch2_journal_read_device+0x8fd/0xab0 [bcachefs]
[   20.474709]  ? pick_next_task_fair+0x32/0x350
[   20.474711]  process_one_work+0x1cc/0x3a0
[   20.474713]  worker_thread+0x4a/0x3c0
[   20.474714]  ? process_one_work+0x3a0/0x3a0
[   20.474716]  kthread+0xfc/0x130
[   20.474718]  ? kthread_park+0x90/0x90
[   20.474719]  ret_from_fork+0x1f/0x30
[   20.474721] Mem-Info:
[   20.474725] active_anon:1047 inactive_anon:120 isolated_anon:0
                active_file:43715 inactive_file:252154 isolated_file:0
                unevictable:0 dirty:8 writeback:0
                slab_reclaimable:4428 slab_unreclaimable:8580
                mapped:1298 shmem:201 pagetables:45 bounce:0
                free:5723247 free_pcp:4393 free_cma:0
[   20.474728] Node 0 active_anon:4188kB inactive_anon:480kB active_file:174860kB inactive_file:1008616kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:5192kB dirty:32kB writeback:0kB shmem:804kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB all_unreclaimable? no
[   20.474731] DMA free:15900kB min:84kB low:104kB high:124kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15996kB managed:15900kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[   20.474731] lowmem_reserve[]: 0 2926 23982 23982 23982
[   20.474735] DMA32 free:2993980kB min:16484kB low:20604kB high:24724kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:3087508kB managed:3002176kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:4084kB local_pcp:1308kB free_cma:0kB
[   20.474736] lowmem_reserve[]: 0 0 21055 21055 21055
[   20.474740] Normal free:19883108kB min:118592kB low:148240kB high:177888kB reserved_highatomic:0KB active_anon:4188kB inactive_anon:480kB active_file:174860kB inactive_file:1008616kB unevictable:0kB writepending:32kB present:22007296kB managed:21561016kB mlocked:0kB kernel_stack:3488kB pagetables:180kB bounce:0kB free_pcp:13488kB local_pcp:1404kB free_cma:0kB
[   20.474740] lowmem_reserve[]: 0 0 0 0 0
[   20.474742] DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (U) 3*4096kB (M) = 15900kB
[   20.474748] DMA32: 15*4kB (UM) 12*8kB (M) 14*16kB (UM) 12*32kB (UM) 17*64kB (UM) 16*128kB (UM) 10*256kB (UM) 9*512kB (UM) 9*1024kB (UM) 10*2048kB (M) 721*4096kB (M) = 2993980kB
[   20.474754] Normal: 779*4kB (UME) 601*8kB (UM) 226*16kB (UM) 123*32kB (UME) 88*64kB (UME) 44*128kB (UME) 28*256kB (UME) 14*512kB (UM) 7*1024kB (UM) 5*2048kB (ME) 4840*4096kB (UM) = 19883124kB
[   20.474760] 296068 total pagecache pages
[   20.474768] 0 pages in swap cache
[   20.474769] Swap cache stats: add 0, delete 0, find 0/0
[   20.474770] Free swap  = 48835564kB
[   20.474770] Total swap = 48835564kB
[   20.474771] 6277700 pages RAM
[   20.474771] 0 pages HighMem/MovableOnly
[   20.474771] 132927 pages reserved

**Comment by jpsollie** [comment]
after a reboot, the error message changed:
ˋˋˋ
[  179.886626] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sde sector 1043456 seq 16630: journal checksum bad, fixing
[  179.886631] bcachefs (3cf34905-b04f-449c-b3c0-93f686c4bda9): sde sector 1043616 seq 144959613534272244: unknown journal entry version 1118932277, fixing
[  180.039784] BUG: unable to handle page fault for address: ffff88863f380000
[  180.039801] #PF: supervisor read access in kernel mode
[  180.039811] #PF: error_code(0x0000) - not-present page
[  180.039819] PGD b7e01067 P4D b7e01067 PUD b7e04067 PMD 63f1fc067 PTE 0
[  180.039832] Oops: 0000 [#1] SMP NOPTI
[  180.039839] CPU: 5 PID: 225 Comm: kworker/u32:10 Not tainted 5.8.3+ #2
[  180.039850] Hardware name: Gigabyte Technology Co., Ltd. X570 UD/X570 UD, BIOS F20 07/07/2020
[  180.039874] Workqueue: events_unbound bch2_journal_read_device [bcachefs]
[  180.039888] RIP: 0010:__memcpy+0x12/0x20
[  180.039894] Code: 00 b8 01 00 00 00 85 d2 74 0a c7 05 24 0e 96 00 0f 00 00 00 f3 c3 cc cc 0f 1f 44 00 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 <f3> 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 f3 a4
[  180.039929] RSP: 0018:ffff88861904bda0 EFLAGS: 00010246
[  180.039938] RAX: ffffc90010001018 RBX: ffffc90010001000 RCX: 00000000015fb305
[  180.039950] RDX: 0000000000000000 RSI: ffff88863f380000 RDI: ffffc90056a2d018
[  180.039962] RBP: ffff88861904be68 R08: 0000000000051a06 R09: 000000000000001c
[  180.039975] R10: 8000000000000163 R11: ffffc900056a1000 R12: 0000000000000008
[  180.039987] R13: ffff8885f8954000 R14: ffff888601480000 R15: ffff8886220d9c78
[  180.039999] FS:  0000000000000000(0000) GS:ffff888626d40000(0000) knlGS:0000000000000000
[  180.040014] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  180.040023] CR2: ffff88863f380000 CR3: 000000060b58e000 CR4: 00000000001406e0
[  180.040035] Call Trace:
[  180.040045]  bch2_journal_read_device+0x69d/0xab0 [bcachefs]
[  180.040058]  ? pick_next_task_fair+0x32/0x350
[  180.040065]  process_one_work+0x1cc/0x3a0
[  180.040072]  worker_thread+0x4a/0x3c0
[  180.040078]  ? process_one_work+0x3a0/0x3a0
[  180.040086]  kthread+0xfc/0x130
[  180.040091]  ? kthread_park+0x90/0x90
[  180.040097]  ret_from_fork+0x1f/0x30
[  180.040103] Modules linked in: btrfs blake2b_generic lzo_compress lzo_decompress ses enclosure bcachefs lz4_compress crc64 lz4_decompress xor raid6_pq input_leds led_class it87 hwmon_vid hid_generic usbhid i2c_piix4 hid aacraid tpm_crb tpm_tis tpm_tis_core pinctrl_amd wmi tpm efivarfs
[  180.040157] CR2: ffff88863f380000
[  180.040163] ---[ end trace 3f64bb92f1246df0 ]---
[  180.082961] RIP: 0010:__memcpy+0x12/0x20
[  180.082968] Code: 00 b8 01 00 00 00 85 d2 74 0a c7 05 24 0e 96 00 0f 00 00 00 f3 c3 cc cc 0f 1f 44 00 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 <f3> 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 f3 a4
[  180.083004] RSP: 0018:ffff88861904bda0 EFLAGS: 00010246
[  180.083013] RAX: ffffc90010001018 RBX: ffffc90010001000 RCX: 00000000015fb305
[  180.083026] RDX: 0000000000000000 RSI: ffff88863f380000 RDI: ffffc90056a2d018
[  180.083038] RBP: ffff88861904be68 R08: 0000000000051a06 R09: 000000000000001c
[  180.083050] R10: 8000000000000163 R11: ffffc900056a1000 R12: 0000000000000008
[  180.083063] R13: ffff8885f8954000 R14: ffff888601480000 R15: ffff8886220d9c78
[  180.083075] FS:  0000000000000000(0000) GS:ffff888626d40000(0000) knlGS:0000000000000000
[  180.083585] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  180.084099] CR2: ffff88863f380000 CR3: 000000060b58e000 CR4: 00000000001406e0
ˋˋˋ

Is this the info you need?

**Comment by jpsollie** [comment]
To close this topic: I regenerated the filesystem from scratch, so sorry, not able to provide debug info any longer ...
