### ISSUE TITLE
BUG: unable to handle page fault for address, related to btree_node_mem_ptr_optimization

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#291]
```
2021-07-26T21:47:42.707792+02:00 zserwerek kernel: [   42.210047] BUG: unable to handle page fault for address: ffff8b2925b1b490
2021-07-26T21:47:42.707792+02:00 zserwerek kernel: [   42.210056] #PF: supervisor read access in kernel mode
2021-07-26T21:47:42.707796+02:00 zserwerek kernel: [   42.210060] #PF: error_code(0x0000) - not-present page
2021-07-26T21:47:42.707797+02:00 zserwerek kernel: [   42.210063] PGD 0 P4D 0
2021-07-26T21:47:42.707798+02:00 zserwerek kernel: [   42.210067] Oops: 0000 [#1] SMP DEBUG_PAGEALLOC NOPTI
2021-07-26T21:47:42.707799+02:00 zserwerek kernel: [   42.210071] CPU: 0 PID: 1831 Comm: mount Not tainted 5.13.0-00836-g4c8bc927e354 #7
2021-07-26T21:47:42.707799+02:00 zserwerek kernel: [   42.210077] Hardware name: MSI MS-7982/B150M PRO-VDH (MS-7982), BIOS 3.H0 07/10/2018
2021-07-26T21:47:42.707800+02:00 zserwerek kernel: [   42.210081] RIP: 0010:__lock_acquire+0x5aa/0x1eb0
2021-07-26T21:47:42.707805+02:00 zserwerek kernel: [   42.210087] Code: 89 84 24 70 09 00 00 0f 87 87 05 00 00 3b 05 e1 87 d5 01 41 bf 01 00 00 00 0f 86 f2 00 00 00 89 05 cf 87 d5 01 e9 e7 00 00 00 <48> 81 3f 80 cf c3 bb b
9 00 00 00 00 41 0f 45 c8 83 fe 01 0f 87 97
2021-07-26T21:47:42.707806+02:00 zserwerek kernel: [   42.210096] RSP: 0018:ffffafff41987848 EFLAGS: 00010002
2021-07-26T21:47:42.707807+02:00 zserwerek kernel: [   42.210100] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000001
2021-07-26T21:47:42.707807+02:00 zserwerek kernel: [   42.210105] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff8b2925b1b490
2021-07-26T21:47:42.707808+02:00 zserwerek kernel: [   42.210109] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
2021-07-26T21:47:42.707808+02:00 zserwerek kernel: [   42.210112] R10: 0000000000000000 R11: 000000000005666f R12: ffff8cc6d05c0000
2021-07-26T21:47:42.707813+02:00 zserwerek kernel: [   42.210116] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
2021-07-26T21:47:42.707814+02:00 zserwerek kernel: [   42.210120] FS:  00007f202c089740(0000) GS:ffff8cc7e4800000(0000) knlGS:0000000000000000
2021-07-26T21:47:42.707815+02:00 zserwerek kernel: [   42.210126] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
2021-07-26T21:47:42.707815+02:00 zserwerek kernel: [   42.210130] CR2: ffff8b2925b1b490 CR3: 0000000104954004 CR4: 00000000003706f0
2021-07-26T21:47:42.707816+02:00 zserwerek kernel: [   42.210134] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
2021-07-26T21:47:42.707816+02:00 zserwerek kernel: [   42.210138] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
2021-07-26T21:47:42.707817+02:00 zserwerek kernel: [   42.210142] Call Trace:
2021-07-26T21:47:42.707821+02:00 zserwerek kernel: [   42.210145]  ? bch2_alloc_read_fn+0xb1/0x1a0
2021-07-26T21:47:42.707822+02:00 zserwerek kernel: [   42.210152]  ? bch2_btree_and_journal_iter_peek+0x4a/0x210
2021-07-26T21:47:42.707823+02:00 zserwerek kernel: [   42.210158]  lock_acquire+0xbb/0x2b0
2021-07-26T21:47:42.707823+02:00 zserwerek kernel: [   42.210162]  ? bch2_btree_node_get_noiter+0x61/0x2b0
2021-07-26T21:47:42.707824+02:00 zserwerek kernel: [   42.210168]  ? bch2_btree_cache_count+0x40/0x40
2021-07-26T21:47:42.707825+02:00 zserwerek kernel: [   42.210171]  six_lock_read+0x39/0x120
2021-07-26T21:47:42.707829+02:00 zserwerek kernel: [   42.210176]  ? bch2_btree_node_get_noiter+0x61/0x2b0
2021-07-26T21:47:42.707830+02:00 zserwerek kernel: [   42.210179]  ? sched_clock_cpu+0xc/0xb0
2021-07-26T21:47:42.707830+02:00 zserwerek kernel: [   42.210185]  bch2_btree_node_get_noiter+0x61/0x2b0
2021-07-26T21:47:42.707831+02:00 zserwerek kernel: [   42.210190]  bch2_btree_and_journal_walk_recurse.isra.0+0x15d/0x310
2021-07-26T21:47:42.707832+02:00 zserwerek kernel: [   42.210195]  ? bch2_alloc_unpack+0x180/0x180
2021-07-26T21:47:42.707832+02:00 zserwerek kernel: [   42.210203]  ? bch2_alloc_unpack+0x180/0x180
2021-07-26T21:47:42.707837+02:00 zserwerek kernel: [   42.210207]  bch2_btree_and_journal_walk+0x49/0x60
2021-07-26T21:47:42.707838+02:00 zserwerek kernel: [   42.210212]  bch2_alloc_read+0x2f/0x50
2021-07-26T21:47:42.707838+02:00 zserwerek kernel: [   42.210217]  bch2_fs_recovery+0x90f/0xff0
2021-07-26T21:47:42.707839+02:00 zserwerek kernel: [   42.210222]  ? bch2_get_next_online_dev+0x1a4/0x2b0
2021-07-26T21:47:42.707839+02:00 zserwerek kernel: [   42.210227]  ? __closure_wake_up+0xf/0x50
2021-07-26T21:47:42.707840+02:00 zserwerek kernel: [   42.210232]  bch2_fs_start+0x29f/0x3d0
2021-07-26T21:47:42.707841+02:00 zserwerek kernel: [   42.210238]  bch2_fs_open+0x320/0x3d0
2021-07-26T21:47:42.707845+02:00 zserwerek kernel: [   42.210241]  ? sget+0x27c/0x2a0
2021-07-26T21:47:42.707846+02:00 zserwerek kernel: [   42.210246]  bch2_mount+0x548/0x710
2021-07-26T21:47:42.707846+02:00 zserwerek kernel: [   42.210254]  legacy_get_tree+0x2d/0x50
2021-07-26T21:47:42.707847+02:00 zserwerek kernel: [   42.210258]  vfs_get_tree+0x20/0x90
2021-07-26T21:47:42.707870+02:00 zserwerek kernel: [   42.210262]  path_mount+0x743/0xb10
2021-07-26T21:47:42.707871+02:00 zserwerek kernel: [   42.210267]  __x64_sys_mount+0x103/0x140
2021-07-26T21:47:42.707876+02:00 zserwerek kernel: [   42.210272]  do_syscall_64+0x5e/0xb0
2021-07-26T21:47:42.707877+02:00 zserwerek kernel: [   42.210278]  ? rcu_read_lock_sched_held+0x3f/0x70
2021-07-26T21:47:42.707877+02:00 zserwerek kernel: [   42.210283]  ? lockdep_hardirqs_on_prepare+0xd4/0x170
2021-07-26T21:47:42.707878+02:00 zserwerek kernel: [   42.210288]  ? do_syscall_64+0x6e/0xb0
2021-07-26T21:47:42.707879+02:00 zserwerek kernel: [   42.210292]  ? rcu_read_lock_sched_held+0x3f/0x70
2021-07-26T21:47:42.707879+02:00 zserwerek kernel: [   42.210297]  entry_SYSCALL_64_after_hwframe+0x44/0xae
2021-07-26T21:47:42.707880+02:00 zserwerek kernel: [   42.210302] RIP: 0033:0x7f202c1b90ea
2021-07-26T21:47:42.707884+02:00 zserwerek kernel: [   42.210306] Code: 48 8b 0d 81 bd 0b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 49 89 ca b8 a5 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 4e bd 0b 00 f7 d8 64 89 01 48
2021-07-26T21:47:42.707885+02:00 zserwerek kernel: [   42.210315] RSP: 002b:00007fffdd32df78 EFLAGS: 00000246 ORIG_RAX: 00000000000000a5
2021-07-26T21:47:42.707886+02:00 zserwerek kernel: [   42.210320] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007f202c1b90ea
2021-07-26T21:47:42.707886+02:00 zserwerek kernel: [   42.210324] RDX: 000056221e6a66b0 RSI: 000056221e6a6960 RDI: 000056221e6a68f0
2021-07-26T21:47:42.707887+02:00 zserwerek kernel: [   42.210328] RBP: 000056221e6a3440 R08: 000056221e6a67a0 R09: 0000000000000000
2021-07-26T21:47:42.707888+02:00 zserwerek kernel: [   42.210332] R10: 0000000000000400 R11: 0000000000000246 R12: 0000000000000000
2021-07-26T21:47:42.707892+02:00 zserwerek kernel: [   42.210336] R13: 000056221e6a68f0 R14: 000056221e6a66b0 R15: 00007f202c2afc02
2021-07-26T21:47:42.707893+02:00 zserwerek kernel: [   42.210342] Modules linked in: pcrypt nf_nat_ftp nf_conntrack_ftp nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 coretemp hwmon i915 x86_pkg_temp_thermal intel_powerclamp i2c_algo_bit kvm_intel intel_gtt iosf_mbi drm_kms_helper cfbfillrect syscopyarea cfbimgblt sysfillrect sysimgblt kvm fb_sys_fops cfbcopyarea fb snd_pcsp snd_pcm irqbypass font fbdev snd_timer rapl intel_cstate snd drm soundcore intel_uncore r8169 realtek mdio_devres of_mdio mei_me i2c_i801 intel_lpss_pci fixed_phy i2c_smbus intel_lpss bfq idma64 i2c_core virt_dma libphy drm_panel_orientation_quirks mei intel_pch_thermal mfd_core video backlight acpi_pad button fan thermal raid1 md_mod crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel xhci_pci xhci_hcd mpt3sas aesni_intel crypto_simd cryptd raid_class scsi_transport_sas dm_mod
2021-07-26T21:47:42.707894+02:00 zserwerek kernel: [   42.210415] CR2: ffff8b2925b1b490
2021-07-26T21:47:42.707895+02:00 zserwerek kernel: [   42.210419] ---[ end trace c8bc393917a0ad51 ]---
2021-07-26T21:47:42.707895+02:00 zserwerek kernel: [   42.210422] RIP: 0010:__lock_acquire+0x5aa/0x1eb0
2021-07-26T21:47:42.707899+02:00 zserwerek kernel: [   42.210426] Code: 89 84 24 70 09 00 00 0f 87 87 05 00 00 3b 05 e1 87 d5 01 41 bf 01 00 00 00 0f 86 f2 00 00 00 89 05 cf 87 d5 01 e9 e7 00 00 00 <48> 81 3f 80 cf c3 bb b9 00 00 00 00 41 0f 45 c8 83 fe 01 0f 87 97
2021-07-26T21:47:42.707901+02:00 zserwerek kernel: [   42.210435] RSP: 0018:ffffafff41987848 EFLAGS: 00010002
2021-07-26T21:47:42.707901+02:00 zserwerek kernel: [   42.210438] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000001
2021-07-26T21:47:42.707902+02:00 zserwerek kernel: [   42.210442] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff8b2925b1b490
2021-07-26T21:47:42.707902+02:00 zserwerek kernel: [   42.210446] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
2021-07-26T21:47:42.707903+02:00 zserwerek kernel: [   42.210450] R10: 0000000000000000 R11: 000000000005666f R12: ffff8cc6d05c0000
2021-07-26T21:47:42.707909+02:00 zserwerek kernel: [   42.210454] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
2021-07-26T21:47:42.707910+02:00 zserwerek kernel: [   42.210457] FS:  00007f202c089740(0000) GS:ffff8cc7e4800000(0000) knlGS:0000000000000000
2021-07-26T21:47:42.707911+02:00 zserwerek kernel: [   42.210462] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
2021-07-26T21:47:42.707911+02:00 zserwerek kernel: [   42.210466] CR2: ffff8b2925b1b490 CR3: 0000000104954004 CR4: 00000000003706f0
2021-07-26T21:47:42.707912+02:00 zserwerek kernel: [   42.210470] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
2021-07-26T21:47:42.707913+02:00 zserwerek kernel: [   42.210473] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
```

filesystem mounts without error with ` -o nobtree_node_mem_ptr_optimization`

**Comment by marcin-github** [comment]
It stroke me again after unclean shutdown.

**Comment by koverstreet** [comment]
Fixed by dc5f2e2d02

**Comment by marcin-github** [comment]
Hmm, it looks it's not fixed.
I'm on commit 6fd8b4b9fbaa but
```
[  123.406652] bcachefs (dm-4): journal read done, 864447 keys in 4922 entries, seq 886076
[  124.312669] BUG: unable to handle page fault for address: ffff96696bb53890
[  124.312691] #PF: supervisor read access in kernel mode
[  124.312703] #PF: error_code(0x0000) - not-present page
[  124.312715] PGD 0 P4D 0
[  124.312727] Oops: 0000 [#1] SMP DEBUG_PAGEALLOC NOPTI
[  124.312741] CPU: 3 PID: 1878 Comm: mount Not tainted 5.13.0-00856-g6fd8b4b9fbaa #12
[  124.312760] Hardware name: MSI MS-7982/B150M PRO-VDH (MS-7982), BIOS 3.H0 07/10/2018
[  124.312774] RIP: 0010:__lock_acquire+0x5aa/0x1eb0
[  124.312793] Code: 89 84 24 70 09 00 00 0f 87 87 05 00 00 3b 05 e1 87 d5 01 41 bf 01 00 00 00 0f 86 f2 00 00 00 89 05 cf 87 d5 01 e9 e7 00 00 00 <48> 81 3f 80 cf c3 ba b9 00 00 00 00 41 0f 45 c8 83 fe 01 0f 87 97
[  124.312823] RSP: 0018:ffff96c901a27878 EFLAGS: 00010002
[  124.312837] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000001
[  124.312851] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff96696bb53890
[  124.312864] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
[  124.312877] R10: 0000000000000000 R11: 00000000000014f1 R12: ffff8b31fafd4000
[  124.312890] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[  124.312903] FS:  00007f7876d33740(0000) GS:ffff8b3324e00000(0000) knlGS:0000000000000000
[  124.312920] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  124.312933] CR2: ffff96696bb53890 CR3: 00000001221ae005 CR4: 00000000003706e0
[  124.312947] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  124.312959] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  124.312973] Call Trace:
[  124.312983]  ? mark_held_locks+0x45/0x70
[  124.313001]  lock_acquire+0xbb/0x2b0
[  124.313015]  ? bch2_btree_node_get_noiter+0x6a/0x2b0
[  124.313034]  ? bch2_btree_cache_count+0x40/0x40
[  124.313047]  six_lock_read+0x39/0x120
[  124.313062]  ? bch2_btree_node_get_noiter+0x6a/0x2b0
[  124.313076]  bch2_btree_node_get_noiter+0x6a/0x2b0
[  124.313092]  bch2_btree_and_journal_walk_recurse.isra.0+0x15d/0x310
[  124.313111]  ? bch2_alloc_unpack+0x180/0x180
[  124.313136]  ? bch2_alloc_unpack+0x180/0x180
[  124.313151]  bch2_btree_and_journal_walk+0x49/0x60
[  124.313168]  bch2_alloc_read+0x2f/0x50
[  124.313183]  bch2_fs_recovery+0x90f/0x1020
[  124.313200]  ? bch2_get_next_online_dev+0x1a4/0x2b0
[  124.313217]  ? __closure_wake_up+0xf/0x50
[  124.313233]  bch2_fs_start+0x29f/0x3d0
[  124.313251]  bch2_fs_open+0x320/0x3d0
[  124.313263]  ? sget+0x27c/0x2a0
[  124.313279]  bch2_mount+0x548/0x710
[  124.313303]  legacy_get_tree+0x2d/0x50
[  124.313317]  vfs_get_tree+0x20/0x90
[  124.313330]  path_mount+0x743/0xb10
[  124.313346]  __x64_sys_mount+0x103/0x140
[  124.313362]  do_syscall_64+0x5e/0xb0
[  124.313374]  ? rcu_read_lock_sched_held+0x3f/0x70
[  124.313391]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[  124.313407] RIP: 0033:0x7f7876e630ea
[  124.313421] Code: 48 8b 0d 81 bd 0b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 49 89 ca b8 a5 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 4e bd 0b 00 f7 d8 64 89 01 48
[  124.313450] RSP: 002b:00007fff74ec0808 EFLAGS: 00000246 ORIG_RAX: 00000000000000a5
[  124.313468] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007f7876e630ea
[  124.313482] RDX: 0000556a35bdf840 RSI: 0000556a35be07a0 RDI: 0000556a35be0ab0
[  124.313495] RBP: 0000556a35bdd440 R08: 0000000000000000 R09: 0000000000000001
[  124.313508] R10: 0000000000200000 R11: 0000000000000246 R12: 0000000000000000
[  124.313521] R13: 0000556a35be0ab0 R14: 0000556a35bdf840 R15: 00007f7876f59c02
[  124.313541] Modules linked in: pcrypt nf_nat_ftp nf_conntrack_ftp nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 coretemp hwmon i915 x86_pkg_temp_thermal intel_powerclamp kvm_intel i2c_algo_bit intel_gtt iosf_mbi drm_kms_helper kvm cfbfillrect syscopyarea cfbimgblt sysfillrect sysimgblt fb_sys_fops cfbcopyarea snd_pcsp fb r8169 snd_pcm font fbdev irqbypass rapl realtek mdio_devres drm intel_cstate snd_timer of_mdio fixed_phy snd i2c_i801 intel_uncore soundcore i2c_smbus libphy bfq mei_me i2c_core intel_lpss_pci drm_panel_orientation_quirks mei intel_lpss intel_pch_thermal idma64 virt_dma mfd_core thermal fan video backlight button acpi_pad raid1 md_mod crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel aesni_intel crypto_simd xhci_pci cryptd xhci_hcd mpt3sas raid_class scsi_transport_sas dm_mod
[  124.313771] CR2: ffff96696bb53890
[  124.313781] ---[ end trace ec1a5fddcc6f2504 ]---
[  124.313792] RIP: 0010:__lock_acquire+0x5aa/0x1eb0
[  124.313807] Code: 89 84 24 70 09 00 00 0f 87 87 05 00 00 3b 05 e1 87 d5 01 41 bf 01 00 00 00 0f 86 f2 00 00 00 89 05 cf 87 d5 01 e9 e7 00 00 00 <48> 81 3f 80 cf c3 ba b9 00 00 00 00 41 0f 45 c8 83 fe 01 0f 87 97
[  124.313836] RSP: 0018:ffff96c901a27878 EFLAGS: 00010002
[  124.313848] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000001
[  124.313861] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff96696bb53890
[  124.313873] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
[  124.313885] R10: 0000000000000000 R11: 00000000000014f1 R12: ffff8b31fafd4000
[  124.313898] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[  124.313911] FS:  00007f7876d33740(0000) GS:ffff8b3324e00000(0000) knlGS:0000000000000000
[  124.313927] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  124.313938] CR2: ffff96696bb53890 CR3: 00000001221ae005 CR4: 00000000003706e0
[  124.313952] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  124.313964] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  128.447862] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
```

**Comment by koverstreet** [comment]
Fixed for real in 3ab44d9452
