### ISSUE TITLE
invalid bkey on insert from bch2_journal_replay during fsck upgrade [202b20c]

### ISSUE THREAD

**Issue by collinmay** [koverstreet/bcachefs#404]
**Version**

Tools [d256ebaa81b554305b57e9967626d53f399a1452](https://github.com/koverstreet/bcachefs-tools/tree/d256ebaa81b554305b57e9967626d53f399a1452), bcachefs sources updated to 202b20c48f6fa96de566d71b6e1a27e0de00d341.

**Generic info**
**`bcachefs fs usage`:** n/a, can't mount

**`bcachefs show-super:`**
<details>

```
External UUID:                  8dec553b-0062-4620-81b1-d424f2d54219
Internal UUID:                  80692c32-36f1-4f98-8a16-c64475fc12ea
Device index:                   3
Label:                          
Version:                        freespace
Oldest version on disk:         inode_v2
Created:                        Sun May 17 18:07:00 2020
Sequence number:                1661
Superblock size:                13776
Clean:                          0
Devices:                        5
Sections:                       journal,members,replicas_v0,disk_groups,clean,journal_seq_blacklist
Features:                       atomic_nlink,journal_seq_blacklist_v3,reflink,new_siphash,inline_data,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,reflink_inline_data,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4k
  btree_node_size:              256k
  errors:                       continue [ro] panic 
  metadata_replicas:            2
  data_replicas:                2
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64k
  metadata_checksum:            none [crc32c] crc64 xxhash 
  data_checksum:                none [crc32c] crc64 xxhash 
  compression:                  [none] lz4 gzip zstd 
  background_compression:       [none] lz4 gzip zstd 
  str_hash:                     crc32c crc64 [siphash] 
  metadata_target:              none
  foreground_target:            fast
  background_target:            slow
  promote_target:               fast
  erasure_code:                 0
  inodes_32bit:                 0
  shard_inode_numbers:          0
  inodes_use_key_cache:         0
  gc_reserve_percent:           8
  gc_reserve_bytes:             0
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        1000
  journal_transaction_names:    0

members (size 288):
  Device:                       0
    UUID:                       fc0b1211-e49b-4886-9042-78ae75a80ce1
    Size:                       90G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    368640
    Last mount:                 Sun Apr 10 16:24:08 2022
    State:                      rw
    Group:                      slow (3)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       1
    UUID:                       9164e55b-d104-46d5-94e5-29beabed8102
    Size:                       1.9T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    4042797
    Last mount:                 Sun Apr 10 16:24:08 2022
    State:                      rw
    Group:                      slow (3)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       2
    UUID:                       1e59299a-6bf1-47ab-8ea9-509be4d78069
    Size:                       1.3T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    2790458
    Last mount:                 Sun Apr 10 16:24:08 2022
    State:                      rw
    Group:                      slow (3)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       3
    UUID:                       61114b6b-626d-439c-9a6d-994ff08dd8b3
    Size:                       2.7T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    5723174
    Last mount:                 Sun Apr 10 16:24:08 2022
    State:                      rw
    Group:                      slow (3)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
  Device:                       4
    UUID:                       17099efa-430e-45a5-81fe-517ff5eff70d
    Size:                       1.8T
    Bucket size:                1M
    First bucket:               0
    Buckets:                    1906704
    Last mount:                 Sun Apr 10 16:24:08 2022
    State:                      rw
    Group:                      fast (2)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user,cached
    Discard:                    0
    Freespace initialized:      1
```
</details>

**Output:**
`gdb -ex run --args ./bcachefs fsck /dev/sda1 /dev/sdb3 /dev/sdc1 /dev/sdd2 /dev/nvme0n1p2`

```
checking need_discard and freespace btrees
going read-write
invalid bkey on insert from bch2_journal_replay -> 0x5577a4bc3245s
  u64s 11 type alloc_v4 1:1569718:0 len 0 ver 0: gen 2 oldest_gen 1 data_type cached journal_seq 31907441 need_discard 0 need_inc_gen 0 dirty_sectors 0 cached_sectors 64 stripe 0 stripe_redundancy 0 read_time 0 write_time 0
  cached bucket with read_time == 0
inconsistency detected - emergency read only
transaction updates for bch2_journal_replay journal seq 0
  update: btree alloc 0x5577a4bc3245S
    old u64s 11 type alloc_v4 1:1569718:0 len 0 ver 0: gen 2 oldest_gen 1 data_type cached journal_seq 31907441 need_discard 0 need_inc_gen 0 dirty_sectors 0 cached_sectors 64 stripe 0 stripe_redundancy 0 read_time 0 write_time 0
    new u64s 11 type alloc_v4 1:1569718:0 len 0 ver 0: gen 2 oldest_gen 1 data_type cached journal_seq 31907441 need_discard 0 need_inc_gen 0 dirty_sectors 0 cached_sectors 64 stripe 0 stripe_redundancy 0 read_time 0 write_time 0

journal replay: error -22 while replaying key at btree alloc level 0
Error in recovery: journal replay failed (-22)
```

Full output: [fsck_out.txt.gz](https://github.com/koverstreet/bcachefs/files/8460241/fsck_out.txt.gz)
</details>

**Comment by koverstreet** [comment]
I fixed this earlier today - update kernel and -tools to the latest version and reopen if it's still there

**Comment by collinmay** [comment]
Yeah, I'm still seeing this with latest versions. Same commits as mentioned in the issue, fresh rebuilds.

**Comment by koverstreet** [comment]
Ah, the update must be from the repair code then. Patch will be up shortly.

**Comment by koverstreet** [comment]
See if that patch fixes it for you

**Comment by collinmay** [comment]
It does indeed. Thank you very much :)
