### ISSUE TITLE
kernel BUG at fs/bcachefs/btree_locking.h:296! [f6170331097d]

### ISSUE THREAD

**Issue by FlyingWombat** [koverstreet/bcachefs#444]
With this version, fsck panicked on a debug assert at `fs/bcachefs/btree_locking.h:296`
Maybe related to #443 , but according to the dmesg log this happened earlier, while checking extents to backpointers, instead of checking the extents themselves.

dmesg log: 
[bcachefs-5.19.0-gf6170331097d-fsck-fail.txt](https://github.com/koverstreet/bcachefs/files/9305667/bcachefs-5.19.0-gf6170331097d-fsck-fail.txt)

**Version**
bcachefs v5.19.0 f6170331097d389e6e44f683a8f131b99d51254c

**Generic info**
superblock: 
[bcachefs-superblock_2022-08-06.txt](https://github.com/koverstreet/bcachefs/files/9305662/bcachefs-superblock_2022-08-06.txt)
12th-gen Intel ibt=off
Debug build

**Comment by koverstreet** [comment]
Fixed by 9d12488720

**Comment by FlyingWombat** [comment]
FYI: that commit did not fix (tested using ad9ab2d7c96bee8cd3cf4bfe5e62249f88e5517a, which followed it); but as of commit 90a9c61e2bcf20935aebda1c0c8078ad0fff2475 it is fixed.

**Comment by FlyingWombat** [comment]
Now its back in commit 327dbbdb0caf4bc0ca8f294cb914b71870caf850
Except, it's fs/bcachefs/btree_locking.h:308 now, instead of line 296 -- same function/statement, just the line number changed.

**Comment by FlyingWombat** [comment]
I am thoroughly confused, because I'm hitting this assert on 90a9c61e2bcf20935aebda1c0c8078ad0fff2475 now too -- using the same kernel build artifact as before, all running `mount -o verbose,fsck,fix_errors,nochanges. And this whole week I've only ever mounted using nochanges, because fsck has been failing.

Here are tracebacks hitting this assert, on builds for all of the commits I've mentioned here.
To my eyes, these all look about the same (except fsck1194 obviously).
Here are the logs:
[bcachefs-5.19.1-g90a9c61e2bcf-fsck-fail_btree_locking296.txt](https://github.com/koverstreet/bcachefs/files/9329486/bcachefs-5.19.1-g90a9c61e2bcf-fsck-fail_btree_locking296.txt)
[bcachefs-5.19.1-g90a9c61e2bcf-fsck-fail_fsck1194.txt](https://github.com/koverstreet/bcachefs/files/9329488/bcachefs-5.19.1-g90a9c61e2bcf-fsck-fail_fsck1194.txt)
[bcachefs-5.19.1-g327dbbdb0caf-fsck-fail_btree_locking308.txt](https://github.com/koverstreet/bcachefs/files/9329501/bcachefs-5.19.1-g327dbbdb0caf-fsck-fail_btree_locking308.txt)
[bcachefs-5.19.1-g49c34dadcad9-fsck-fail_btree_locking296.txt](https://github.com/koverstreet/bcachefs/files/9329505/bcachefs-5.19.1-g49c34dadcad9-fsck-fail_btree_locking296.txt)
[bcachefs-5.19.1-gad9ab2d7c96b-fsck-fail_btree_locking296.txt](https://github.com/koverstreet/bcachefs/files/9329516/bcachefs-5.19.1-gad9ab2d7c96b-fsck-fail_btree_locking296.txt)



Let me know if there's other info I can get for you.
