### ISSUE TITLE
Build errors on x86_64 with CONFIG_BCACHEFS_FS=m

### ISSUE THREAD

**Issue by hardfalcon** [koverstreet/bcachefs#467]
This issue likely affects all architectures and build-time configurations that include building the documenation since it appears to be an RST syntax error:
* https://github.com/koverstreet/bcachefs/commit/548335ae2b59660d76ce36ff33b68cad72ced6da#r85973299

//EDIT: Sorry for the noise, the two other ancient bugs that I had mentioned have actually been resolved since somewhere between 2022-08-25 and 2022-08-31.

**Comment by BlackLotus** [comment]
Thanks the fix you linked to worked for me.

**Comment by bhzhu203** [comment]
mm/filemap.c
line 2914  add this :

```
 EXPORT_SYMBOL(mapping_seek_hole_data);
```

**Comment by hardfalcon** [comment]
@bhzhu203: Thank you.

Turns out that two of the other "bugs" I had previously mentioned when initially opening this Github issue had actually already been resolved since somewhere between 2022-08-25 and 2022-08-31. I had been carrying dirty hacks/workarounds for them since for quite a time and had never noticed that they had actually been fixed in the meantime. Sorry for the noise, my bad. 🙈

**Comment by koverstreet** [comment]
Fixed by 9f6a92530c

**Comment by hardfalcon** [comment]
@koverstreet: I'm sorry but the issue I mentioned in my initial posting is not fixed and still produces a syntax error when I run `make htmldocs`:
```sh
$ make htmldocs
[…]
/tmp/linux-bcachefs/Documentation/core-api/printk-formats.rst:642: ERROR: Unexpected indentation.
```

This is caused by a syntax error in [line 638](https://github.com/koverstreet/bcachefs/commit/548335ae2b59660d76ce36ff33b68cad72ced6da#r85973299), where [two colons instead of only one would be required](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks) at the end of the line. Adding the second colon at the end of line 638 fixes the issue.

**Comment by hardfalcon** [comment]
Solved in https://github.com/koverstreet/bcachefs/commit/88548589fc3f1f6cd72a4592f573e4dd61fded59, thanks! :)
