### ISSUE TITLE
hard kernel panic: trans iter overflow

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#72]
Getting a hard kernel panic upon mounting with latest master (ce9293e9d063f7f1a22209f9cc2f5cb7478e886c) but also earlier commits.
bcachefs repeatedly logs `bcachefs: btree_trans_iter_alloc() iter: btree extents pos 55546:5328 live keep` to journal before the panic.
Here is a photo of the stack trace:
![callstack](https://user-images.githubusercontent.com/9434715/66248890-d7abbb00-e71b-11e9-8926-c2b296680012.jpg)
Dump is contained in these files:
https://drive.google.com/open?id=1e1uS3jctfPepIwGD6yvBGMA0_MgAoYny
https://drive.google.com/open?id=12w2OspswUYqeZuuj9eWXi7UXQAXAg3Ol

**Comment by hyperfekt** [comment]
Still occurs on ce9c3373f2936da244dc80e945e2dc944fd23fec.

**Comment by koverstreet** [comment]
Should be fixed by b83dba0d3 bcachefs: Fix incorrect use of bch2_extent_atomic_end()

**Comment by hyperfekt** [comment]
Still getting this when trying to use the KDE application launcher on the same filesystem as the prior report on commit b83dba0d3fde8d424a274a0936d9c436d770b3aa.
Note the typo in the panic message, oveflow vs overflow.
<details><summary>Log</summary><pre><code>
<3>[ 6790.292212] bcachefs: btree_trans_iter_alloc() iter: btree extents pos 953270:31384 live keep
<3>[ 6790.292215] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82712 touched keep
<3>[ 6790.292216] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82776 touched keep
<3>[ 6790.292217] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:80664
<3>[ 6790.292218] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:80792
<3>[ 6790.292219] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83032 touched keep
<3>[ 6790.292220] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2101088 touched keep
<3>[ 6790.292221] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:80920
<3>[ 6790.292221] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81048
<3>[ 6790.292222] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81096
<3>[ 6790.292223] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81216
<3>[ 6790.292224] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81312
<3>[ 6790.292225] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81440
<3>[ 6790.292225] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81568
<3>[ 6790.292226] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81696
<3>[ 6790.292227] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81784
<3>[ 6790.292228] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81824
<3>[ 6790.292229] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82584 touched keep
<3>[ 6790.292229] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:81952
<3>[ 6790.292230] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82112
<3>[ 6790.292231] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:21515
<3>[ 6790.292232] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:71964 touched keep
<3>[ 6790.292233] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83160 touched keep
<3>[ 6790.292234] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:12915
<3>[ 6790.292235] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82200
<3>[ 6790.292235] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83288 touched keep
<3>[ 6790.292236] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:174987 touched keep
<3>[ 6790.292237] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82328
<3>[ 6790.292238] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:82400
<3>[ 6790.292239] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83568 touched keep
<3>[ 6790.292240] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:139200 touched keep
<3>[ 6790.292241] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:324503 touched
<3>[ 6790.292241] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:240987 touched keep
<3>[ 6790.292242] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2101080 touched keep
<3>[ 6790.292243] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2072240 touched keep
<3>[ 6790.292244] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83760 touched keep
<3>[ 6790.292245] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2074928 touched keep
<3>[ 6790.292246] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2074952 touched keep
<3>[ 6790.292247] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:83888 touched keep
<3>[ 6790.292247] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:84232 touched keep
<3>[ 6790.292248] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2140040 touched keep
<3>[ 6790.292249] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:84352 touched keep
<3>[ 6790.292250] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:84480 touched keep
<3>[ 6790.292251] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:80536
<3>[ 6790.292251] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:84608 touched keep
<3>[ 6790.292252] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:60298
<3>[ 6790.292253] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:532591 touched keep
<3>[ 6790.292254] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:84632 touched
<3>[ 6790.292255] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:255601 touched keep
<3>[ 6790.292256] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:21516
<3>[ 6790.292257] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:18383 touched
<3>[ 6790.292257] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:60299 touched keep
<3>[ 6790.292258] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:139232 touched keep
<3>[ 6790.292259] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:139248 touched keep
<3>[ 6790.292260] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2100632 touched keep
<3>[ 6790.292261] bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:2101272 touched
<3>[ 6790.292262] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:71965 touched keep
<3>[ 6790.292262] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:453276 touched keep
<3>[ 6790.292263] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:71966 touched keep
<3>[ 6790.292264] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:60300 touched keep
<3>[ 6790.292265] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:453253 touched keep
<3>[ 6790.292266] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:709918 touched keep
<3>[ 6790.292267] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:127905 touched
<3>[ 6790.292267] bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:255602 touched keep
<0>[ 6790.292268] Kernel panic - not syncing: trans iter oveflow
<4>[ 6790.292270] CPU: 1 PID: 1789 Comm: .plasmashell-wr Not tainted 5.2.0 #1-NixOS
<4>[ 6790.292271] Hardware name: Dell Inc. Latitude E5470/0C8FKJ, BIOS 1.19.3 08/20/2018
<4>[ 6790.292272] Call Trace:
<4>[ 6790.292278]  dump_stack+0x5c/0x80
<4>[ 6790.292281]  panic+0x101/0x2c8
<4>[ 6790.292291]  btree_trans_iter_alloc.cold.48+0x83/0x83 [bcachefs]
<4>[ 6790.292300]  __btree_trans_get_iter+0x3ab/0x4b0 [bcachefs]
<4>[ 6790.292308]  bch2_trans_get_iter+0x29/0x80 [bcachefs]
<4>[ 6790.292318]  trans_get_key.constprop.57+0x11e/0x190 [bcachefs]
<4>[ 6790.292327]  bch2_trans_mark_pointer+0xc7/0x410 [bcachefs]
<4>[ 6790.292336]  bch2_trans_mark_extent+0x1cd/0x4a0 [bcachefs]
<4>[ 6790.292345]  ? trans_get_key.constprop.57+0x150/0x190 [bcachefs]
<4>[ 6790.292353]  ? bch2_btree_iter_set_pos+0x4b/0xa0 [bcachefs]
<4>[ 6790.292362]  ? trans_get_key.constprop.57+0x150/0x190 [bcachefs]
<4>[ 6790.292371]  bch2_trans_mark_key+0x8d/0x390 [bcachefs]
<4>[ 6790.292381]  bch2_trans_mark_update+0x9f/0x410 [bcachefs]
<4>[ 6790.292391]  ? bch2_extent_atomic_end+0x23d/0x290 [bcachefs]
<4>[ 6790.292400]  bch2_trans_commit+0x3f3/0x18b0 [bcachefs]
<4>[ 6790.292410]  bch2_btree_delete_at_range+0x14f/0x1e0 [bcachefs]
<4>[ 6790.292418]  bch2_btree_delete_range+0xac/0xf0 [bcachefs]
<4>[ 6790.292427]  ? bch2_btree_delete_range+0x3b/0xf0 [bcachefs]
<4>[ 6790.292436]  ? bch2_trans_fs_usage_apply+0x4f/0xa0 [bcachefs]
<4>[ 6790.292443]  ? __bch2_btree_node_iter_fix+0x38e/0x700 [bcachefs]
<4>[ 6790.292449]  ? bch2_bset_fix_lookup_table+0x286/0x4e0 [bcachefs]
<4>[ 6790.292455]  ? bset_aux_tree_verify+0x83/0xf0 [bcachefs]
<4>[ 6790.292463]  ? bch2_btree_node_iter_fix+0x184/0x2a0 [bcachefs]
<4>[ 6790.292469]  ? __bch2_time_stats_update+0x84/0x140 [bcachefs]
<4>[ 6790.292478]  ? bch2_trans_commit+0x1de/0x18b0 [bcachefs]
<4>[ 6790.292488]  bch2_inode_rm+0xb8/0x3b0 [bcachefs]
<4>[ 6790.292499]  ? bch2_unlink+0xc8/0x240 [bcachefs]
<4>[ 6790.292502]  ? _cond_resched+0x15/0x30
<4>[ 6790.292504]  ? kmem_cache_alloc+0x14a/0x1b0
<4>[ 6790.292507]  ? avc_compute_av.cold.17+0x34/0x34
<4>[ 6790.292516]  ? bch2_inode_update_after_write+0x1fa/0x210 [bcachefs]
<4>[ 6790.292526]  ? bch2_vfs_inode_init+0x91/0x170 [bcachefs]
<4>[ 6790.292528]  ? _cond_resched+0x15/0x30
<4>[ 6790.292530]  ? dput.part.34+0x29/0x130
<4>[ 6790.292532]  ? __inode_wait_for_writeback+0x7f/0xf0
<4>[ 6790.292535]  ? init_wait_var_entry+0x40/0x40
<4>[ 6790.292536]  evict+0xc6/0x190
<4>[ 6790.292538]  do_unlinkat+0x26a/0x320
<4>[ 6790.292541]  do_syscall_64+0x4e/0x130
<4>[ 6790.292542]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
<4>[ 6790.292544] RIP: 0033:0x7fec8d881c87
<4>[ 6790.292546] Code: f0 ff ff 73 01 c3 48 8b 0d f6 91 0c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 66 90 b8 57 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d c9 91 0c 00 f7 d8 64 89 01 48
<4>[ 6790.292547] RSP: 002b:00007ffefe931b28 EFLAGS: 00000206 ORIG_RAX: 0000000000000057
<4>[ 6790.292549] RAX: ffffffffffffffda RBX: 00007ffefe931b70 RCX: 00007fec8d881c87
<4>[ 6790.292550] RDX: 0000000000000002 RSI: 00000000058a4360 RDI: 00000000058a4378
<4>[ 6790.292551] RBP: 0000000005dcf020 R08: 0000000000000020 R09: 000000000000005b
<4>[ 6790.292552] R10: 00007fec8a294d90 R11: 0000000000000206 R12: 00000000059bd060
<4>[ 6790.292552] R13: 00007ffefe931cb0 R14: 00007ffefe931c90 R15: 00007ffefe931c98
<0>[ 6790.292594] Kernel Offset: 0x24c00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
</code></pre></details>

**Comment by hyperfekt** [comment]
Seems fixed with 75fab77a82c22a4b447923f70fe8c7316249de1d. That was quick!

**Comment by stintel** [comment]
Just hit this on recent master, definitely newer than b83dba0 (can't get the exact commit as I am running master + linux-stable/v5.2.20 and am hitting the panic during mount at boot time.

```
[   54.047691] Kernel panic - not syncing: trans iter oveflow
[   54.053190] CPU: 4 PID: 4911 Comm: mount Tainted: G                T 5.2.20-00240-gccb4a4359152 #1
[   54.062161] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./E3C224D4I-14S, BIOS P3.20 05/29/2015
[   54.072086] Call Trace:
[   54.074545]  dump_stack+0x46/0x68
[   54.077864]  panic+0x107/0x2d7
[   54.080935]  btree_trans_iter_alloc.cold.6+0x3a/0xca [bcachefs]
[   54.086880]  __btree_trans_get_iter+0x34b/0x490 [bcachefs]
[   54.092381]  bch2_trans_get_iter+0x41/0xa0 [bcachefs]
[   54.097449]  trans_get_key.constprop.7+0x12d/0x1a0 [bcachefs]
[   54.103207]  bch2_trans_mark_key+0x23c/0x390 [bcachefs]
[   54.108458]  bch2_trans_mark_update+0x1ee/0x390 [bcachefs]
[   54.113960]  bch2_trans_commit+0x430/0x14e0 [bcachefs]
[   54.119116]  bch2_btree_delete_at_range+0x195/0x1e0 [bcachefs]
[   54.124959]  bch2_btree_delete_range+0xc5/0x110 [bcachefs]
[   54.130463]  ? bch2_btree_delete_range+0x54/0x110 [bcachefs]
[   54.136139]  bch2_inode_rm+0xfd/0x3d0 [bcachefs]
[   54.140776]  check_inode+0x2f2/0x690 [bcachefs]
[   54.145325]  bch2_fsck_walk_inodes_only+0x155/0x170 [bcachefs]
[   54.151177]  ? bch2_fsck_walk_inodes_only+0x55/0x170 [bcachefs]
[   54.157112]  bch2_fs_recovery+0xe08/0x1010 [bcachefs]
[   54.162182]  ? bch2_fs_start+0x45b/0x4d0 [bcachefs]
[   54.167075]  bch2_fs_start+0x45b/0x4d0 [bcachefs]
[   54.171791]  bch2_fs_open+0x251/0x2c0 [bcachefs]
[   54.176809]  bch2_mount+0x2b9/0x6d0 [bcachefs]
[   54.181661]  legacy_get_tree+0x27/0x50
[   54.185805]  vfs_get_tree+0x28/0xc0
[   54.189679]  do_mount+0x77f/0x980
[   54.193372]  ? memdup_user+0x4b/0x70
[   54.197323]  ksys_mount+0xb6/0xd0
[   54.201007]  __x64_sys_mount+0x22/0x30
[   54.205150]  do_syscall_64+0x63/0x190
[   54.209179]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   54.214615] RIP: 0033:0x7f23853084ce
[   54.218570] Code: 89 f6 b8 b0 00 00 00 0f 05 48 89 c7 e8 3b e6 ff ff 48 83 c4 08 c3 66 0f 1f 44 00 00 48 83 ec 08 49 89 ca b8 a5 00 00 00 0f 05 <48> 89 c7 e8 1a e6 ff ff 48 83 c4 08 c3 0f 1f 44 00 00 48 83 ec 08
[   54.238106] RSP: 002b:00007ffde25b6550 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[   54.246055] RAX: ffffffffffffffda RBX: 00007f23853a6ae0 RCX: 00007f23853084ce
[   54.253580] RDX: 00007f23853a6ee0 RSI: 00007f23853a6ec0 RDI: 00007f2385287d60
[   54.261128] RBP: 00007f23852e5230 R08: 0000000000000000 R09: 8080808080808080
[   54.268654] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
[   54.276199] R13: 0000000000000000 R14: 00007f2385287d60 R15: 00007f23853a6ee0
[   54.283769] Kernel Offset: 0x38000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[   54.297045] ---[ end Kernel panic - not syncing: trans iter oveflow ]---
```

**Comment by stintel** [comment]
fsck (bcachefs-tools 7f3557f57efb6e22aa90fdaca481907f633ceb08) fails too:

```
ministore /usr/src/bcachefs-tools # ./bcachefs fsck -n /dev/disk/by-id/wwn-0x5000cca27075ebbc /dev/disk/by-id/ata-Samsung_SSD_860_PRO_1TB_S42NNF0M403593R-part4
journal read done, 327961 keys in 47 entries, seq 13533821
starting metadata mark and sweep
starting mark and sweep
bcachefs: btree_trans_iter_alloc() iter: btree extents pos 28870:28837056 live touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29862368 touched
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29862368 touched
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860320 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860448 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860576 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860704 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860832 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:605701 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29862368 touched
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29861600 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:17151757 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:720880 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:17186111 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1129314 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:75786 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:17186112 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29862400 touched
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:382886 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:839850 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:15834333 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10363212 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10377820 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:804426 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:15819582 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1628774 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1509966 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860128 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29861480 touched
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10311898 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:75671 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1239273 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1237562 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10363213 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1598127 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:17082087 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:342973 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1620409 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10326091 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:901306 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10312027 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:17005495 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1066328 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10311416 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29861728 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29861856 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29861920 touched
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:917945 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:13618 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10309685 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1623560 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1625578 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree reflink pos 0:29860192 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1031709 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10310754 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:541908 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:883461 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:541887 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1134790 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1625580 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10310780 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:10310920 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 1:1625826 touched keep
bcachefs: btree_trans_iter_alloc() iter: btree alloc pos 0:1117537 touched keep
trans iter oveflow
Assertion failed: 0 (libbcachefs/btree_iter.c: btree_trans_iter_alloc: 1860)
Aborted
```

**Comment by stintel** [comment]
Tried to mount it with b83dba0d3fde as that worked for @hyperfekt but still getting a panic.

**Comment by stintel** [comment]
Still getting a panic on 910ede36bbeb480fa6a9ab15b5138f6286eb7f2a + linux-stable/v5.2.20: 

```
[  160.108458] Kernel panic - not syncing: trans iter oveflow
[  160.113959] CPU: 0 PID: 11735 Comm: mount Tainted: G                T 5.2.20-00247-g228b78511b7a #1
[  160.123015] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./E3C224D4I-14S, BIOS P3.20 05/29/2015
[  160.132942] Call Trace:
[  160.135402]  dump_stack+0x46/0x68
[  160.138727]  panic+0x107/0x2d7
[  160.141802]  btree_trans_iter_alloc.cold.6+0x3a/0xca [bcachefs]
[  160.147738]  __btree_trans_get_iter+0x34b/0x490 [bcachefs]
[  160.153249]  bch2_trans_get_iter+0x41/0xa0 [bcachefs]
[  160.158314]  trans_get_key.constprop.7+0x12d/0x1a0 [bcachefs]
[  160.164080]  bch2_trans_mark_extent+0x3b4/0x1030 [bcachefs]
[  160.169668]  ? bch2_btree_iter_peek_slot+0x26e/0x770 [bcachefs]
[  160.175606]  ? bch2_btree_iter_peek_slot+0x26e/0x770 [bcachefs]
[  160.181541]  ? trans_get_key.constprop.7+0xe1/0x1a0 [bcachefs]
[  160.187393]  bch2_trans_mark_key+0xa8/0x390 [bcachefs]
[  160.192571]  bch2_trans_mark_update+0xd8/0x390 [bcachefs]
[  160.197981]  bch2_trans_commit+0x430/0x14e0 [bcachefs]
[  160.203130]  bch2_btree_delete_at_range+0x1a6/0x1f0 [bcachefs]
[  160.208981]  bch2_btree_delete_range+0xc5/0x110 [bcachefs]
[  160.214482]  ? bch2_btree_delete_range+0x54/0x110 [bcachefs]
[  160.220164]  bch2_inode_rm+0xfd/0x3d0 [bcachefs]
[  160.224798]  check_inode+0x2f2/0x690 [bcachefs]
[  160.229369]  bch2_fsck_walk_inodes_only+0x155/0x170 [bcachefs]
[  160.235216]  ? bch2_fsck_walk_inodes_only+0x55/0x170 [bcachefs]
[  160.241155]  bch2_fs_recovery+0xe08/0x1010 [bcachefs]
[  160.246223]  ? bch2_fs_start+0x45b/0x4d0 [bcachefs]
[  160.251116]  bch2_fs_start+0x45b/0x4d0 [bcachefs]
[  160.255852]  bch2_fs_open+0x251/0x2c0 [bcachefs]
[  160.260504]  bch2_mount+0x2b9/0x6c0 [bcachefs]
[  160.264961]  legacy_get_tree+0x27/0x50
[  160.268717]  vfs_get_tree+0x28/0xc0
[  160.272219]  do_mount+0x78b/0x980
[  160.275539]  ? memdup_user+0x4b/0x70
[  160.279137]  ksys_mount+0xb6/0xd0
[  160.282462]  __x64_sys_mount+0x22/0x30
[  160.286217]  do_syscall_64+0x63/0x190
[  160.289891]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  160.294953] RIP: 0033:0x7ff7c10a54ce
[  160.298547] Code: 89 f6 b8 b0 00 00 00 0f 05 48 89 c7 e8 3b e6 ff ff 48 83 c4 08 c3 66 0f 1f 44 00 00 48 83 ec 08 49 89 ca b8 a5 00 00 00 0f 05 <48> 89 c7 e8 1a e6 ff ff 48 83 c4 08 c3 0f 1f 44 00 00 48 83 ec 08
[  160.317332] RSP: 002b:00007ffc2b788550 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[  160.324910] RAX: ffffffffffffffda RBX: 00007ff7c1143ae0 RCX: 00007ff7c10a54ce
[  160.332049] RDX: 00007ff7c11437c0 RSI: 00007ff7c1143e60 RDI: 00007ff7c11437e0
[  160.339191] RBP: 00007ff7c1082230 R08: 0000000000000000 R09: 8080808080808080
[  160.346762] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
[  160.354319] R13: 0000000000000000 R14: 00007ff7c11437e0 R15: 00007ff7c11437c0
[  160.361923] Kernel Offset: 0x3a000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[  160.375918] ---[ end Kernel panic - not syncing: trans iter oveflow ]---
```

**Comment by stintel** [comment]
(Adding for completeness)

Even with de906c3e2eddad291d46bd0e7c81c68eaadcd08a I still got kernel panic when trying to mount:
```
[  104.914443] Kernel panic - not syncing: trans iter oveflow
[  104.919953] CPU: 4 PID: 11101 Comm: mount Tainted: G                T 5.2.20-00249-ga74ff601bc20 #1
[  104.929012] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./E3C224D4I-14S, BIOS P3.20 05/29/2015
[  104.938945] Call Trace:
[  104.941412]  dump_stack+0x46/0x68
[  104.944739]  panic+0x107/0x2d7
[  104.947822]  btree_trans_iter_alloc.cold.6+0x3a/0xca [bcachefs]
[  104.953768]  __btree_trans_get_iter+0x34b/0x490 [bcachefs]
[  104.959278]  bch2_trans_get_iter+0x41/0xa0 [bcachefs]
[  104.964348]  trans_get_key.constprop.7+0x12d/0x1a0 [bcachefs]
[  104.970118]  bch2_trans_mark_extent+0x3b4/0x1030 [bcachefs]
[  104.975702]  ? _raw_spin_lock_irqsave+0x15/0x20
[  104.980256]  ? bch2_btree_iter_peek_slot+0x26e/0x770 [bcachefs]
[  104.986196]  ? bch2_btree_iter_peek_slot+0x26e/0x770 [bcachefs]
[  104.992141]  ? trans_get_key.constprop.7+0xd1/0x1a0 [bcachefs]
[  104.997999]  bch2_trans_mark_key+0xa8/0x390 [bcachefs]
[  105.003167]  bch2_trans_mark_update+0xd8/0x390 [bcachefs]
[  105.008583]  bch2_trans_commit+0x430/0x14e0 [bcachefs]
[  105.013738]  bch2_btree_delete_at_range+0x1a6/0x1f0 [bcachefs]
[  105.019599]  bch2_btree_delete_range+0xc5/0x110 [bcachefs]
[  105.025107]  ? bch2_btree_delete_range+0x54/0x110 [bcachefs]
[  105.030790]  bch2_inode_rm+0xfd/0x3d0 [bcachefs]
[  105.035434]  check_inode+0x2f2/0x690 [bcachefs]
[  105.039992]  bch2_fsck_walk_inodes_only+0x155/0x170 [bcachefs]
[  105.045850]  ? bch2_fsck_walk_inodes_only+0x55/0x170 [bcachefs]
[  105.051799]  bch2_fs_recovery+0xe08/0x1010 [bcachefs]
[  105.056871]  ? bch2_fs_start+0x45b/0x4d0 [bcachefs]
[  105.061766]  bch2_fs_start+0x45b/0x4d0 [bcachefs]
[  105.066506]  bch2_fs_open+0x251/0x2c0 [bcachefs]
[  105.071152]  bch2_mount+0x2b9/0x6f0 [bcachefs]
[  105.075609]  legacy_get_tree+0x27/0x40
[  105.079375]  vfs_get_tree+0x28/0xc0
[  105.082877]  do_mount+0x2aa/0x980
[  105.086212]  ? memdup_user+0x4b/0x70
[  105.089804]  ksys_mount+0xb6/0xd0
[  105.093137]  __x64_sys_mount+0x22/0x30
[  105.096898]  do_syscall_64+0x63/0x190
[  105.100576]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  105.105639] RIP: 0033:0x7f40e77c84ce
[  105.109232] Code: 89 f6 b8 b0 00 00 00 0f 05 48 89 c7 e8 3b e6 ff ff 48 83 c4 08 c3 66 0f 1f 44 00 00 48 83 ec 08 49 89 ca b8 a5 00 00 00 0f 05 <48> 89 c7 e8 1a e6 ff ff 48 83 c4 08 c3 0f 1f 44 00 00 48 83 ec 08
[  105.128013] RSP: 002b:00007fff311f4050 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[  105.135594] RAX: ffffffffffffffda RBX: 00007f40e7866ae0 RCX: 00007f40e77c84ce
[  105.142742] RDX: 00007f40e78667c0 RSI: 00007f40e7866e60 RDI: 00007f40e78667e0
[  105.150321] RBP: 00007f40e77a5230 R08: 0000000000000000 R09: 8080808080808080
[  105.157901] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
[  105.165494] R13: 0000000000000000 R14: 00007f40e78667e0 R15: 00007f40e78667c0
[  105.173436] Kernel Offset: 0x15000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[  105.187321] ---[ end Kernel panic - not syncing: trans iter oveflow ]---```

At the same time, `fsck -n` was passing. Eventually tried `fsck` without `-n`. The first time it crashed:
```
Assertion failed: 0 (libbcachefs/btree_iter.c: btree_trans_iter_alloc: 1865)
```
When I ran fsck after that, it passed, and I was able to mount the fs.

**Comment by koverstreet** [comment]
I believe all the iterator overflow bugs are finally fixed (at least for now); b0519a5d7d should have finally fixed the last of it.
