### ISSUE TITLE
Can't mount after unclean shutdown

### ISSUE THREAD

**Issue by brauliobo** [koverstreet/bcachefs#741]
On a slow WD 4tb HDD, after the reboot processing hanging on bcachefs, I triggered a reset on the hardware. Then after reboot the volume doesn't mount anymore, below is the dmesg output.

Using 6.10.6 before reboot and 6.10.7 after

```
[22657.512238] bcachefs (sdc1): bch2_fs_recovery(): error ERESTARTSYS
[22657.512243] bcachefs (sdc1): bch2_fs_start(): error starting filesystem ERESTARTSYS
[22657.512443] bcachefs (sdc1): unshutdown complete, journal seq 1471481
[22657.541789] bcachefs: bch2_mount() error: ERESTARTSYS
[22773.846412] bcachefs (sdc1): mounting version 1.7: mi_btree_bitmap opts=compression=zstd:15
[22773.846416] bcachefs (sdc1): recovering from unclean shutdown
[22845.839949] bcachefs (sdc1): journal read done, replaying entries 1467829-1471480
[22845.839954] bcachefs (sdc1): dropped unflushed entries 1471481-1471481
[22848.745005] bcachefs (sdc1): alloc_read... done
[22848.745153] bcachefs (sdc1): stripes_read... done
[22848.745156] bcachefs (sdc1): snapshots_read... done
[22848.922685] bcachefs (sdc1): going read-write
[22848.923649] bcachefs (sdc1): journal_replay...
[22863.912626] bcachefs (/dev/sdc1): error reading superblock: error opening /dev/sdc1: EBUSY
[22863.912631] bcachefs: bch2_mount() error: EBUSY
[22931.034245]  done
```

**Comment by gkmcd** [comment]
Lately I haven't been able to cleanly unmount my bcachefs filesystem. It always reports filesystem busy, despite no activity on the mountpoint (verified with iptop and fuser).

If I use umount -l, I get ERESTARTSYS when remounting the system on reboot. I have to manually mount with -o fsck,fix_errors.
```
sudo dmesg | grep bcachefs
[   12.525118] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): starting version 1.12: rebalance_work_acct_fix opts=metadata_replicas=2,data_replicas=2,compression=zstd,foreground_target=ssd,background_target=hdd,promote_target=ssd
[   12.525124] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): recovering from unclean shutdown
[   58.442880] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): journal read done, replaying entries 14385364-14393543
[   58.442890] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): dropped unflushed entries 14393544-14393544
[   64.833104] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): accounting_read... done
[   65.209593] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): alloc_read... done
[   66.844870] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): stripes_read... done
[   66.844883] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): snapshots_read... done
[   67.843142] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): going read-write
[   67.857339] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): journal_replay... done
[  162.988107] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): bch2_fs_recovery(): error ERESTARTSYS
[  162.988274] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): bch2_fs_start(): error starting filesystem ERESTARTSYS
[  162.989238] bcachefs (32b2df91-1683-4288-9ebf-e60d104cc069): unshutdown complete, journal seq 14393642
[  163.099338] bcachefs: bch2_fs_get_tree() error: ERESTARTSYS
```

**Comment by koverstreet** [comment]
Ok that's odd, we'll have to track down where that -ERESTARTSYS is coming from

**Comment by koverstreet** [comment]
ahh, it's from the wait_event_interruptible() in bch2_journal_flush_seq()

**Comment by koverstreet** [comment]
Try my bcachefs-for-upstream branch

**Comment by koverstreet** [comment]
This should be fixed

**Comment by gkmcd** [comment]
OK, awesome. I've done a lot of yak-shaving with not much spare time but still haven't managed to boot the testing kernel yet.

**Comment by brauliobo** [comment]
Was this fix backported to 6.11.x series? I'm still not able to remount USB external drives, even if unmounted cleanly
